project_id = "nipyiixaksdovswqwsfj"

[functions.verify-solana-payment]
verify_jwt = false

[functions.process-winner-payout]
verify_jwt = false

[functions.process-refund]
verify_jwt = false

[functions.matchmaking-service]
verify_jwt = false